#!/usr/bin/env bash
# Displays "Holberton School" 10 times, "bad luck" on 4, "good luck" on 8

counter=1
while [ $counter -le 10 ]
do
	if [ $counter = 4 ]
	then
	    echo "bad luck"
	elif [ $counter = 8 ]
	then
	    echo "good luck"
	else
	    echo "Holberton School"
	fi
	((counter++))
done
